version: '3.8'
services:
  zookeeper:
    user: "root"
  kafka-1:
    user: "root"
  kafka-2:
    user: "root"
  kafka-3:
    user: "root"
  vault:
    ports:
      - "8200:8200"
  consul:
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8600:8600"
  redis:
    ports:
      - "36379:6379"
  redis-cache:
    ports:
      - "6380:6379"
  akhq:
    ports:
      - "10100:8080"
  accountant:
    ports:
      - "8089:8080"
      - "1045:5005"
  eventlog:
    ports:
      - "8090:8080"
  matching-engine:
    ports:
      - "8092:8080"
      - "1046:5005"
  matching-gateway:
    ports:
      - "8093:8080"
      - "1047:5005"
  auth:
    ports:
      - "8083:8080"
      - "1048:5005"
  wallet:
    ports:
      - "8091:8080"
      - "1049:5005"
  market:
    ports:
      - "8096:8080"
      - "1056:5005"
  api:
    ports:
      - "8094:8080"
      - "1050:5005"
  bc-gateway:
    ports:
      - "0.0.0.0:8095:8080"
      - "1052:5005"
